services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sikpk-app
    volumes:
      - ./:/var/www/html
    ports:
      - '9000:9000'
      - '5173:5173'
    command: >
      sh -c "
        pnpm install &&
        pnpm dev --host &
        php-fpm
      "
    user: '${UID:-1000}:${GID:-1000}'
    networks:
      - sikpk

  nginx:
    image: nginx:latest
    container_name: sikpk-nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sikpk

  db:
    image: postgres:15-alpine
    container_name: sikpk-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE:-sikpk_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password}
    volumes:
      - sikpk-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sikpk

  atis-adminer:
    image: adminer
    container_name: sikpk-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '9090:8080'
    networks:
      - sikpk

  mail:
    container_name: sikpk-mail
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - sikpk

volumes:
  sikpk-db-data:

networks:
  sikpk:
    name: sikpk-network
