name: Trigger auto deployment for sikpk-app

on:
  push:
    branches:
      - staging
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SIKPKAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SIKPKAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SIKPKAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./docker/azure/Dockerfile
          disableOryxBuild: true
          registryUrl: kota301.azurecr.io
          registryUsername: ${{ secrets.SIKPKAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SIKPKAPP_REGISTRY_PASSWORD }}
          containerAppName: sikpk-app
          resourceGroup: kota301
          imageToBuild: kota301.azurecr.io/sikpk-app:${{ github.sha }}

      - name: Check Revisions
        run: |
          az containerapp revision list \
            --name sikpk-app \
            --resource-group kota301 \
            -o table
